import React, { useEffect, useMemo, useState } from "react";
import AdminLayout from "../AdminLayout";
import { downloadPaystub, getPayroll, hrAction } from "../../../lib/hrApi";
import { computePayrollTotals, regularPayForSalary } from "../../../lib/hr";
import styles from "./Hr.module.css";

const today = new Date().toISOString().slice(0,10);
const lineTypes = [['regular_earnings','Regular earnings'],['additional_earnings','Additional earnings'],['employee_tax','Employee tax'],['pretax_deduction','Pre-tax deduction'],['posttax_deduction','Post-tax deduction'],['reimbursement','Reimbursement'],['employer_tax','Employer tax']];

export default function PayrollManager(){
  const [role,setRole]=useState(null); const [data,setData]=useState({runs:[],paystubs:[],people:[]}); const [runId,setRunId]=useState(''); const [employeeId,setEmployeeId]=useState(''); const [items,setItems]=useState([]); const [form,setForm]=useState({periodStart:today,periodEnd:today,payDate:today,currency:'USD',notes:''}); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false);
  const load=async()=>{const result=await getPayroll();setRole(result.role);setData(result);setRunId((id)=>result.runs.some((r)=>r.id===id)?id:result.runs.find((r)=>r.status==='draft')?.id||result.runs[0]?.id||'');setEmployeeId((id)=>result.people.some((p)=>p.user_id===id)?id:result.people.find((p)=>p.private_profile?.employment_status!=='inactive')?.user_id||'');};
  useEffect(()=>{load().catch((error)=>{setRole('forbidden');setMessage(error.message);});},[]);
  const run=useMemo(()=>data.runs.find((r)=>r.id===runId),[data,runId]); const employee=useMemo(()=>data.people.find((p)=>p.user_id===employeeId),[data,employeeId]); const stub=useMemo(()=>data.paystubs.find((p)=>p.payroll_run_id===runId&&p.user_id===employeeId),[data,runId,employeeId]);
  useEffect(()=>{if(stub?.paystub_line_items?.length)setItems(stub.paystub_line_items);else if(employee?.compensation)setItems([{line_type:'regular_earnings',description:'Regular salary',amount:regularPayForSalary(employee.compensation.annual_salary,employee.compensation.pay_frequency)}]);else setItems([]);},[stub,employeeId,runId]);
  const totals=useMemo(()=>{try{return computePayrollTotals(items);}catch{return null;}},[items]); const perform=async(callback,success)=>{setBusy(true);setMessage('');try{await callback();await load();setMessage(success);}catch(error){setMessage(error.message);}finally{setBusy(false);}};
  const deleteRun=(targetRun)=>{const permanentWarning=targetRun.status==='draft'?'This cannot be undone.':'This permanently deletes the payroll record, every employee paystub, and all stored PDF files. This cannot be undone.';if(window.confirm(`Delete this ${targetRun.status} payroll run for ${targetRun.period_start} through ${targetRun.period_end}? ${permanentWarning}`)){perform(()=>hrAction('delete_payroll_run',{runId:targetRun.id}),targetRun.status==='draft'?'Payroll draft deleted.':'Payroll run and stored PDFs deleted.');}};
  if(role===null)return <AdminLayout title="Payroll" subtitle="Owner-entered payroll records and private paystubs"><div className={styles.card}>Loading payroll…</div></AdminLayout>;
  if(role!=='owner')return <AdminLayout title="Payroll" subtitle="Owner workspace"><div className={styles.alert}>{message||'Owner access is required.'}</div></AdminLayout>;
  return <AdminLayout title="Payroll" subtitle="Owner-entered payroll records and private paystubs">{message&&<div className={`${styles.alert} ${/(created|saved|finalized|paid|voided|deleted)/i.test(message)?styles.success:''}`}>{message}</div>}
    <div className={styles.grid}><section className={`${styles.card} ${styles.full}`}><h2>Create payroll run</h2><div className={styles.formGrid}>{[['periodStart','Period start','date'],['periodEnd','Period end','date'],['payDate','Pay date','date'],['currency','Currency','text']].map(([key,label,type])=><div className={styles.field} key={key}><label>{label}</label><input type={type} maxLength={key==='currency'?3:undefined} className={styles.input} value={form[key]} onChange={(e)=>setForm({...form,[key]:key==='currency'?e.target.value.toUpperCase():e.target.value})}/></div>)}</div><div className={styles.actions}><button className={styles.button} disabled={busy} onClick={()=>perform(async()=>{const result=await hrAction('create_payroll_run',form);setRunId(result.run.id);},'Payroll run created.')}>Create draft</button></div></section>
      <section className={`${styles.card} ${styles.full}`}><h2>Payroll workspace</h2><div className={styles.formGrid}><div className={styles.field}><label>Payroll run</label><select className={styles.select} value={runId} onChange={(e)=>setRunId(e.target.value)}><option value="">Select run</option>{data.runs.map((r)=><option value={r.id} key={r.id}>{r.pay_date} · {r.period_start}–{r.period_end} · {r.status}</option>)}</select></div><div className={styles.field}><label>Employee</label><select className={styles.select} value={employeeId} onChange={(e)=>setEmployeeId(e.target.value)}><option value="">Select employee</option>{data.people.filter((p)=>p.private_profile?.employment_status!=='inactive').map((p)=><option value={p.user_id} key={p.user_id}>{p.first_name} {p.last_name}</option>)}</select></div></div>
      {run&&employee&&<><div className={styles.row} style={{marginTop:16}}><div className={styles.rowMain}><strong>{employee.first_name} {employee.last_name}</strong><span>{employee.compensation?`${employee.compensation.currency} ${employee.compensation.annual_salary} annually · ${employee.compensation.pay_frequency}`:'Salary not configured'}</span></div><span className={styles.badge}>{run.status}</span></div>
      <div style={{marginTop:18}}>{items.map((item,index)=><div className={styles.lineGrid} key={index}><select disabled={run.status!=='draft'} className={styles.select} value={item.line_type} onChange={(e)=>setItems(items.map((old,i)=>i===index?{...old,line_type:e.target.value}:old))}>{lineTypes.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select><input disabled={run.status!=='draft'} className={styles.input} value={item.description} onChange={(e)=>setItems(items.map((old,i)=>i===index?{...old,description:e.target.value}:old))}/><input disabled={run.status!=='draft'} type="number" min="0" step="0.01" className={styles.input} value={item.amount} onChange={(e)=>setItems(items.map((old,i)=>i===index?{...old,amount:e.target.value}:old))}/>{run.status==='draft'&&<button className={`${styles.button} ${styles.danger}`} onClick={()=>setItems(items.filter((_,i)=>i!==index))}>Remove</button>}</div>)}</div>
      {run.status==='draft'&&<div className={styles.actions}><button className={`${styles.button} ${styles.secondary}`} onClick={()=>setItems([...items,{line_type:'additional_earnings',description:'Additional earnings',amount:0}])}>Add line</button><button className={styles.button} disabled={busy||!items.length||!employee.compensation} onClick={()=>perform(()=>hrAction('save_paystub',{runId,userId:employeeId,items}),'Paystub saved.')}>Save paystub</button></div>}
      {totals&&<div className={styles.metricRow} style={{marginTop:18}}><div className={styles.metric}><span>Gross</span><strong>{totals.grossPay.toFixed(2)}</strong></div><div className={styles.metric}><span>Taxes</span><strong>{totals.employeeTaxes.toFixed(2)}</strong></div><div className={styles.metric}><span>Deductions</span><strong>{totals.deductions.toFixed(2)}</strong></div><div className={styles.metric}><span>Net</span><strong>{totals.netPay.toFixed(2)}</strong></div></div>}</>}
      {run&&<div className={styles.actions}>{run.status==='draft'&&<button className={styles.button} disabled={busy||!data.paystubs.some((p)=>p.payroll_run_id===run.id)} onClick={()=>perform(()=>hrAction('finalize_payroll_run',{runId:run.id}),'Payroll finalized and paystubs generated.')}>Finalize run</button>}{run.status==='finalized'&&<button className={styles.button} onClick={()=>perform(()=>hrAction('set_payroll_status',{runId:run.id,status:'paid'}),'Payroll marked paid.')}>Mark paid</button>}{['finalized','paid'].includes(run.status)&&<button className={`${styles.button} ${styles.danger}`} onClick={()=>perform(()=>hrAction('set_payroll_status',{runId:run.id,status:'void'}),'Payroll voided.')}>Void run</button>}{stub?.pdf_path&&<button className={`${styles.button} ${styles.secondary}`} onClick={()=>downloadPaystub(stub)}>Download paystub</button>}<button className={`${styles.button} ${styles.danger}`} disabled={busy} onClick={()=>deleteRun(run)}>{run.status==='draft'?'Delete draft':'Delete run'}</button></div>}</section>
      <section className={`${styles.card} ${styles.full}`}><h2>Payroll history</h2><div className={styles.list}>{data.runs.map((r)=><div className={styles.row} key={r.id}><div className={styles.rowMain}><strong>Pay date {r.pay_date}</strong><span>{r.period_start} – {r.period_end} · {data.paystubs.filter((p)=>p.payroll_run_id===r.id).length} employee(s)</span></div><div className={styles.actions} style={{margin:0}}><span className={`${styles.badge} ${r.status==='void'?styles.badgeDanger:''}`}>{r.status}</span><button className={`${styles.button} ${styles.danger}`} disabled={busy} onClick={()=>deleteRun(r)}>{r.status==='draft'?'Delete draft':'Delete run'}</button></div></div>)}{!data.runs.length&&<div className={styles.empty}>No payroll runs yet.</div>}</div></section>
    </div></AdminLayout>;
}
